export const Demo = {
  discover: [
    {
      title: 'Step-by-Step Guide to Settings - Demo 1',
      image:
        'https://www.minterapp.com/wp-content/uploads/2022/11/image4-1280x640.png',
      likes: 85,
      dislikes: 10,
      views: 1200,
      commentsNum: 5,
      author: {
        name: 'Rock Star',
        avatar: '',
        desc: 'Tech enthusiast and blogger.',
        follower: 1000,
        following: 500,
      },
      createTime: new Date('2024-02-14T08:00:00Z'),
      updateTime: new Date('2024-02-14T08:00:00Z'),
      keywords: ['settings', 'guide', 'tutorial'],
      tags: ['tech', 'settings'],
    },
    {
      title: 'Apple',
      image: 'https://rdrive.org/api/og/?path=/apple/',
      likes: 85,
      dislikes: 10,
      views: 1200,
      commentsNum: 5,
      author: {
        name: 'Rock Star',
        avatar: '',
        desc: 'Tech enthusiast and blogger.',
        follower: 1000,
        following: 500,
      },
      createTime: new Date('2024-02-14T08:00:00Z'),
      updateTime: new Date('2024-02-14T08:00:00Z'),
      keywords: ['settings', 'guide', 'tutorial'],
      tags: ['tech', 'settings'],
    },
    {
      title: 'Exploring Settings for Efficiency - Demo 2',
      image:
        'https://www.foundingminds.com/wp-content/uploads/2023/12/hands-multitasking-with-laptop-notebook-1280x640.jpg',
      likes: 78,
      dislikes: 8,
      views: 950,
      commentsNum: 3,
      author: {
        name: 'Jane Doe',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
        desc: 'Passionate about technology and productivity.',
        follower: 1200,
        following: 600,
      },
      createTime: new Date('2024-02-14T08:00:00Z'),
      updateTime: new Date('2024-02-14T08:00:00Z'),
      keywords: ['efficiency', 'settings', 'productivity'],
      tags: ['technology', 'efficiency'],
    },
    {
      title: 'Mastering Device Settings - Demo 3',
      image:
        'https://www.boat-lifestyle.com/cdn/shop/articles/WhatsApp_Image_2020-10-29_at_6.20.30_PM.jpg',
      likes: 120,
      dislikes: 15,
      views: 1800,
      commentsNum: 7,
      author: {
        name: 'Junior Garcia',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        desc: 'Technology lover and gadget enthusiast.',
        follower: 1500,
        following: 700,
      },
      createTime: new Date('2024-02-14T08:00:00Z'),
      updateTime: new Date('2024-02-14T08:00:00Z'),
      keywords: ['device', 'settings', 'tutorial'],
      tags: ['gadgets', 'technology'],
    },
    {
      title: 'Optimizing Your Experience - Demo 4',
      image:
        'https://www.gizchina.com/wp-content/uploads/images/2020/02/Xiaomi-redmi-note-6-pro-test-xiaotech-1280x640-1.jpg',
      likes: 95,
      dislikes: 5,
      views: 1350,
      commentsNum: 2,
      author: {
        name: 'Bello',
        avatar: 'https://i.pravatar.cc/150?u=a04258a2462d826712d',
        desc: 'Technology enthusiast and content creator.',
        follower: 1800,
        following: 800,
      },
      createTime: new Date('2024-02-14T08:00:00Z'),
      updateTime: new Date('2024-02-14T08:00:00Z'),
      keywords: ['optimization', 'experience', 'settings'],
      tags: ['technology', 'optimization'],
    },
    {
      title: 'Discovering Hidden Settings - Demo 5',
      image:
        'https://worldpodcasts.com/wp-content/uploads/2023/04/Redmi-Note-12-series-1280x640.jpg',
      likes: 150,
      dislikes: 3,
      views: 2000,
      commentsNum: 10,
      author: {
        name: 'Banana',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
        desc: 'Tech enthusiast and blogger.',
        follower: 2000,
        following: 1000,
      },
      createTime: new Date('2024-02-14T08:00:00Z'),
      updateTime: new Date('2024-02-14T08:00:00Z'),
      keywords: ['hidden', 'settings', 'tutorial'],
      tags: ['technology', 'hidden'],
    },
    {
      title: 'Advanced Settings Techniques - Demo 6',
      image:
        'https://worldpodcasts.com/wp-content/uploads/2019/03/mtp-101-pic-1280x640.jpg',
      likes: 130,
      dislikes: 2,
      views: 1700,
      commentsNum: 6,
      author: {
        name: 'Mininons',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026302d',
        desc: 'Passionate about technology and innovation.',
        follower: 2200,
        following: 1000,
      },
      createTime: new Date('2024-02-14T08:00:00Z'),
      updateTime: new Date('2024-02-14T08:00:00Z'),
      keywords: ['hidden', 'settings', 'tutorial'],
      tags: ['technology', 'hidden'],
    },
  ],
  post: [
    {
      title: 'Step-by-Step Guide to Settings - Demo 1',
      img: 'https://www.minterapp.com/wp-content/uploads/2022/11/image4-1280x640.png',
      date: '1 day',
      time: '05:00',
      views: 1200,
      likes: 85,
      href: '/blogs/preview',
    },
    {
      title: 'Exploring Settings for Efficiency - Demo 2',
      img: 'https://www.foundingminds.com/wp-content/uploads/2023/12/hands-multitasking-with-laptop-notebook-1280x640.jpg',
      date: '2 days',
      time: '03:00',
      views: 950,
      likes: 78,
      href: '/blogs/preview',
    },
    {
      title: 'Mastering Device Settings - Demo 3',
      img: 'https://www.boat-lifestyle.com/cdn/shop/articles/WhatsApp_Image_2020-10-29_at_6.20.30_PM.jpg',
      date: '5 days',
      time: '04:00',
      views: 1800,
      likes: 120,
      href: '/blogs/preview',
    },
    {
      title: 'Optimizing Your Experience - Demo 4',
      img: 'https://www.gizchina.com/wp-content/uploads/images/2020/02/Xiaomi-redmi-note-6-pro-test-xiaotech-1280x640-1.jpg',
      date: '1 day',
      time: '03:30',
      views: 1350,
      likes: 95,
      href: '/blogs/preview',
    },
    {
      title: 'Discovering Hidden Settings - Demo 5',
      img: 'https://worldpodcasts.com/wp-content/uploads/2023/04/Redmi-Note-12-series-1280x640.jpg',
      date: '2 days',
      time: '06:00',
      views: 2000,
      likes: 150,
      href: '/blogs/preview',
    },
    {
      title: 'Advanced Settings Techniques - Demo 6',
      img: 'https://worldpodcasts.com/wp-content/uploads/2019/03/mtp-101-pic-1280x640.jpg',
      date: '3 days',
      time: '04:30',
      views: 1700,
      likes: 130,
      href: '/blogs/preview',
    },
  ],
  user: {
    name: 'Rock Star',
    username: 'rockstar',
    bio: 'i wanna die in front of more than billions of people.',
    description: '2 weeks',
    avatar:
      'https://cdn3d.iconscout.com/3d/premium/thumb/boy-7215504-5873316.png',
    post: 10,
    followers: 1200,
    following: 500,
    coverimg: '/images/lyra.png',
    social: [
      { icon: '/social/gmail.png', link: 'http://www.gmail.com' },
      { icon: '/social/youtube.png', link: 'http://www.youtube.com' },
      { icon: '/social/whatsapp.png', link: 'http://wa.me/' },
      { icon: '/social/telegram.png', link: 'http://www.telegram.com' },
      { icon: '/social/github.png', link: 'http://www.github.com' },
    ],
    badge: ['Software', 'Hardware', 'Designer'],
  },
  items: [
    {
      href: '/hello',
      title: 'Apple',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Apple_Computer_Logo_rainbow.svg/412px-Apple_Computer_Logo_rainbow.svg.png',
    },
    {
      href: '/',
      title: 'Asus',
      img: '',
    },
    {
      href: '/',
      title: 'Google',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/2560px-Google_2015_logo.svg.png',
    },
    {
      href: '/',
      title: 'HTC',
      img: 'https://1000logos.net/wp-content/uploads/2021/05/HTC-logo.png',
    },
    {
      href: '/',
      title: 'Xiaomi-12-Pro-(Dimensity-Edition)',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Reliance_Jio_Logo_%28October_2015%29.svg/2048px-Reliance_Jio_Logo_%28October_2015%29.svg.png',
    },
    {
      href: '/',
      title: 'Redmi K20 Pro',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Motorola_logo.svg/2560px-Motorola_logo.svg.png',
    },
  ],
}

export type Demo = typeof Demo
